### ISSUE TITLE
FabricElementAlreadyExistsException thrown when calling a stateful service 

### ISSUE THREAD

**Issue by DeanJMitchell** [Microsoft/ApplicationInsights-ServiceFabric#40]
When using the CorrelatingServiceProxyFactory quite often an FabricElementAlreadyExistsException is thrown.

This has happened during a period of idleness, but can be more easily reproduce by disabling a node and calling the service when it is disabled.

I am not sure exactly which line is throwing the exception but this is an example of us calling one of the services.
var partitionKey = new ServicePartitionKey(partitionId);
var proxyFactory = new CorrelatingServiceProxyFactory(m_context, callbackClient => new FabricTransportServiceRemotingClientFactory(callbackClient: callbackClient));
var userManager = proxyFactory.CreateServiceProxy<IEIUserManagerService>(new Uri("fabric:/EILicenceServer/EIUserManager"), partitionKey);

Exception thrown is:
System.Fabric.FabricElementAlreadyExistsException: Header with name 'ParentId' already exists
   at Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.<InvokeWithRetryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceRemotingPartitionClient.<InvokeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<InvokeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<ContinueWithResult>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EIAuthentication.Controllers.AuthenticationController.<ProcessConcurrencyDuringTokenRenewal>d__29.MoveNext()>",Edm.String,00000000-0000-0000-0000-000000000000,Edm.String,00000000-0000-0000-0000-000000000000,Edm.String,"serviceName=""fabric:/EILicenceServer/EIAuthentication"" serviceTypeName=""EIAuthenticationType"" replicaOrInstanceId=""131537878261862086"" partitionId=""9b523030-c84b-44c7-ab04-8d615a09a0f7"" applicationName=""fabric:/EILicenceServer"" applicationTypeName=""EILicenceServerType"" nodeName=""_nt1vm_1"" message=""AuthenticationController - ProcessConcurrencyDuringTokenRenewal: user:<sip:qa.data@enghouse.com> exception:<System.Fabric.FabricElementAlreadyExistsException: Header with name 'ParentId' already exists
   at Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.<InvokeWithRetryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceRemotingPartitionClient.<InvokeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<InvokeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<ContinueWithResult>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EIAuthentication.Controllers.AuthenticationController.<ProcessConcurrencyDuringTokenRenewal>d__29.MoveNext()>""",Edm.String,636449114244152530,Edm.Int64,0000008800388303185,Edm.String,2017-10-29T22:00:00.000Z,Edm.DateTime

**Comment by mikanyg** [comment]
I have seen the same in our logs

**Comment by karolz-ms** [comment]
Sounds like a bug. We should probably check here https://github.com/Microsoft/ApplicationInsights-ServiceFabric/blob/develop/src/ApplicationInsights.ServiceFabric.Native/Net45/CorrelatingServiceRemotingClient.cs#L131 whether the header exists or not and replace the value when it does, instead of trying to add it.

Thanks for reporting!

**Comment by brahmnes** [comment]
Fix is currently in progress

**Comment by brahmnes** [comment]
Fix in 2.0.1-beta1
